services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - products
      - orders
      - users
    networks:
      - ecommerce_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx -g 'daemon off;'

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./products:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=9001
    networks:
      - ecommerce_network

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    volumes:
      - ./orders:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=9002
    networks:
      - ecommerce_network

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./users:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=9003
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    external: true
